### PR TITLE
update aiohttp behavior

### PR DESCRIPTION
**Pull request by myf**
my wechatircd has stopped working because archlinux has upgraded aiohttp to version 3.0.3 and it has been getting more and more asyncio. this is what i had to do to have the server working again:

changed msg.tp to msg.type
changed aiohttp.web.MsgType.text to aiohttp.WSMsgType.TEXT
changed aiohttp.web.MsgType.close to aiohttp.WSMsgType.CLOSE

added async await for send_message and write function calls

### CODE REVIEW

**Comment by MaskRay** [comment]
It is nice to know it still works. My web wechat has been blocked for the second time :( i was not using IRC, just used a different IP accidentally.

**Comment by myf** [comment]
thanks for the merge. why were you blocked by using a different IP? what is so special about the IP

**Comment by MaskRay** [comment]
Not special. Just used some wifi somewhere else. I think they block accounts imperiously without a good reason.

**Comment by MaskRay** [comment]
Reverted some changes:

```python
-    async def add_member(self, roomname, username):
-        await self.send_command({
+    def add_member(self, roomname, username):
+        self.send_command({
```

Instead of making these functions `async`, it is better to wrap `send_command` with `self.loop.create_task` which I have done in git HEAD. My account had been blocked for some time so I did not test the PR when I merged it :(

**Pull request merged**
